# Commented key are optional,
# otherwise it's necessary

[proxy]
# # SOCKS5 and HTTP(S) are supported
# connection = "http://localhost:3030"

# # proxy authentication
# user = "username"
# password = "p@ssW0Rd"

[telegram]
# Your telegram token, get from @BotFather
token = "139282332:fake_tokenlI_dAF41rNfFsaaa2EJvwi7qL91"
# Enabled groups, either name or id are supported
enabled-chats = ["group_name", "-10011231232"]
